run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    # Essential linters
    - gofmt
    - goimports
    - govet
    - typecheck
    - unused
    - staticcheck
    - gosimple

    # Error checking
    - errcheck

    # Security
    - gosec

    # Code quality
    - ineffassign
    - misspell
    - noctx

linters-settings:
  govet:
    enable:
      - fieldalignment
    disable:
      - shadow

  errcheck:
    check-type-assertions: false
    check-blank: false

  goimports:
    local-prefixes: github.com/dev/personal-finance-tracker/backend

  gosec:
    excludes:
      - G104  # Errors unhandled (use errcheck for this)

  misspell:
    locale: US

issues:
  max-same-issues: 0
  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - noctx
    # Exclude fieldalignment from specific files (minor optimization)
    - path: internal/config/config.go
      linters:
        - govet
    - path: internal/domain/transaction.go
      linters:
        - govet

output:
  formats:
    - format: colored-line-number
  print-linter-name: true
  sort-results: true
